Repository RE-ZERO-In-And-Out/In-And-Out, pull requests merged in 2022-10, with the labels that each got.

#1 Create testfile.txt
  server/testfile.txt
Labels: ✅ Test

#2 folder setting
  client/dummyfile.txt
  server/dummyfile.txt
  server/testfile.txt
Labels: ⚙ Setting

#3 setting-pr-template
  pull_request_template.md
Labels: ⚙ Setting

#5 CHORE/init setting
  server/.gitignore
  server/build.gradle
  server/gradle/wrapper/gradle-wrapper.jar
  server/gradle/wrapper/gradle-wrapper.properties
  server/gradlew
  server/gradlew.bat
  server/settings.gradle
  server/src/main/java/com/rezero/inandout/InandoutApplication.java
  server/src/main/resources/application.properties
  server/src/test/java/com/rezero/inandout/InandoutApplicationTests.java
Labels: ⚙ Setting

#6 FEAT/routing all pages
  client/package-lock.json
  client/package.json
  client/src/.eslintrc.json
  client/src/App.js
  client/src/App.test.js
  client/src/components/Error.js
  client/src/components/layout/LoginSharedLayout.js
  client/src/components/layout/MainSharedLayout.js
  client/src/components/layout/SettingSharedLayout.js
  client/src/components/login/IdentifyEmail.js
  client/src/components/login/IdentifyPhone.js
  client/src/components/login/Login.js
  client/src/components/login/RecoverInitiate.js
  client/src/components/login/Signin.js
  client/src/components/main/Calendar.js
  client/src/components/main/Inout.js
  client/src/components/main/Report.js
  client/src/components/setting/PasswordChange.js
  client/src/components/setting/ProfileChange.js
  client/src/components/setting/Signout.js
  client/src/index.css
  client/src/reportWebVitals.js
  client/src/setupTests.js
Labels: ✨ Feature

#15 Expense 등록 API
  server/src/main/java/com/rezero/inandout/expense/controller/ExpenseController.java
  server/src/main/java/com/rezero/inandout/expense/entity/DetailExpenseCategory.java
  server/src/main/java/com/rezero/inandout/expense/entity/Expense.java
  server/src/main/java/com/rezero/inandout/expense/model/ExpenseDto.java
  server/src/main/java/com/rezero/inandout/expense/model/ExpenseInput.java
  server/src/main/java/com/rezero/inandout/expense/repository/DetailExpenseCategoryRepository.java
  server/src/main/java/com/rezero/inandout/expense/repository/ExpenseCategoryRepository.java
  server/src/main/java/com/rezero/inandout/expense/repository/ExpenseRepository.java
  server/src/main/java/com/rezero/inandout/expense/repository/MonthlyExpenseReportRepository.java
  server/src/main/java/com/rezero/inandout/expense/service/ExpenseService.java
  server/src/main/java/com/rezero/inandout/expense/service/impl/ExpenseServiceImpl.java
  server/src/test/java/com/rezero/inandout/expense/controller/ExpenseControllerTest.java
  server/src/test/java/com/rezero/inandout/expense/service/impl/ExpenseServiceImplTest.java
Labels: ✨ Feature, 📬 API, ✅ Test

#16 Income 등록 API
  server/src/main/java/com/rezero/inandout/income/controller/IncomeController.java
  server/src/main/java/com/rezero/inandout/income/entity/Income.java
  server/src/main/java/com/rezero/inandout/income/model/IncomeInput.java
  server/src/main/java/com/rezero/inandout/income/repository/DetailIncomeCategoryRepository.java
  server/src/main/java/com/rezero/inandout/income/repository/IncomeCategoryRepository.java
  server/src/main/java/com/rezero/inandout/income/repository/IncomeRepository.java
  server/src/main/java/com/rezero/inandout/income/service/IncomeService.java
  server/src/main/java/com/rezero/inandout/income/service/IncomeServiceImpl.java
  server/src/test/java/com/rezero/inandout/income/controller/IncomeControllerTest.java
  server/src/test/java/com/rezero/inandout/income/service/IncomeServiceImplTest.java
Labels: ✨ Feature, 📬 API, ✅ Test

#19 Expense 등록
  server/build.gradle
  server/src/main/resources/application.properties
Labels: ⚙ Setting

#22 FIX/ExpenseControllerTest 수정
  server/src/test/java/com/rezero/inandout/expense/controller/ExpenseControllerTest.java
Labels: 🐞 BugFix

#20 FEAT/validation logic - login page components
  .gitignore
  client/package-lock.json
  client/package.json
  client/src/components/common/Layout.js
  client/src/components/login/IdentifyEmail.js
  client/src/components/login/IdentifyPhone.js
  client/src/components/login/Login.js
  client/src/components/login/RecoverInitiate.js
  client/src/components/login/Signin.js
  client/src/schema/form_validation.js
  package-lock.json
  package.json
Labels: ✨ Feature

#23 FIX/Income 등록 API 코드 수정
  server/src/main/java/com/rezero/inandout/income/model/IncomeInput.java
  server/src/test/java/com/rezero/inandout/income/controller/IncomeControllerTest.java
  server/src/test/java/com/rezero/inandout/income/service/IncomeServiceImplTest.java
Labels: 🐞 BugFix

#24 CHORE/CI 빌드 스크립트 수정
  .github/workflows/react.yml
  client/package-lock.json
  client/package.json
Labels: 🌏 Deploy

#28 FIX/setting pages validation test added
  client/src/components/setting/PasswordChange.js
  client/src/components/setting/ProfileChange.js
  client/src/components/setting/Signout.js
  client/src/img/default-user.png
  client/src/schema/form_validation.js
Labels: ✨ Feature

#26 Expense 조회
  server/src/main/java/com/rezero/inandout/expense/controller/ExpenseController.java
  server/src/main/java/com/rezero/inandout/expense/model/CategoryAndExpenseDto.java
  server/src/main/java/com/rezero/inandout/expense/model/DetailExpenseCategoryDto.java
  server/src/main/java/com/rezero/inandout/expense/model/ExpenseCategoryDto.java
  server/src/main/java/com/rezero/inandout/expense/model/ExpenseDto.java
  server/src/main/java/com/rezero/inandout/expense/repository/DetailExpenseCategoryRepository.java
  server/src/main/java/com/rezero/inandout/expense/repository/ExpenseRepository.java
  server/src/main/java/com/rezero/inandout/expense/service/ExpenseService.java
  server/src/main/java/com/rezero/inandout/expense/service/impl/ExpenseServiceImpl.java
  server/src/test/java/com/rezero/inandout/expense/controller/ExpenseControllerTest.java
  server/src/test/java/com/rezero/inandout/expense/service/impl/ExpenseServiceImplTest.java
Labels: ✨ Feature, 📬 API, ✅ Test

#29 Expense 수정
  server/src/main/java/com/rezero/inandout/expense/model/ExpenseDto.java
  server/src/test/java/com/rezero/inandout/expense/controller/ExpenseControllerTest.java
  server/src/test/java/com/rezero/inandout/expense/service/impl/ExpenseServiceImplTest.java
Labels: 🐞 BugFix

#27 Member 아이디(이메일) / 비밀번호 찾기
  server/src/main/java/com/rezero/inandout/InandoutApplication.java
  server/src/main/java/com/rezero/inandout/member/controller/MemberController.java
  server/src/main/java/com/rezero/inandout/member/entity/Member.java
  server/src/main/java/com/rezero/inandout/member/model/FindPasswordMemberInput.java
  server/src/main/java/com/rezero/inandout/member/repository/MemberRepository.java
  server/src/main/java/com/rezero/inandout/member/service/MemberService.java
  server/src/main/java/com/rezero/inandout/member/service/MemberServiceImpl.java
  server/src/test/java/com/rezero/inandout/member/controller/MemberControllerTest.java
  server/src/test/java/com/rezero/inandout/member/service/MemberServiceImplTest.java
Labels: ✨ Feature, 📬 API, ✅ Test

#30 Income 조회 API
  server/src/main/java/com/rezero/inandout/income/controller/IncomeController.java
  server/src/main/java/com/rezero/inandout/income/entity/DetailIncomeCategory.java
  server/src/main/java/com/rezero/inandout/income/entity/Income.java
  server/src/main/java/com/rezero/inandout/income/entity/IncomeCategory.java
  server/src/main/java/com/rezero/inandout/income/model/CategoryAndIncomeDto.java
  server/src/main/java/com/rezero/inandout/income/model/DetailIncomeCategoryDto.java
  server/src/main/java/com/rezero/inandout/income/model/IncomeCategoryDto.java
  server/src/main/java/com/rezero/inandout/income/model/IncomeDto.java
  server/src/main/java/com/rezero/inandout/income/repository/DetailIncomeCategoryRepository.java
  server/src/main/java/com/rezero/inandout/income/repository/IncomeRepository.java
  server/src/main/java/com/rezero/inandout/income/service/IncomeService.java
  server/src/main/java/com/rezero/inandout/income/service/IncomeServiceImpl.java
  server/src/test/java/com/rezero/inandout/income/controller/IncomeControllerTest.java
  server/src/test/java/com/rezero/inandout/income/service/IncomeServiceImplTest.java
Labels: ✨ Feature, 📬 API, ✅ Test

#34 Expense 수정
  server/src/main/java/com/rezero/inandout/expense/controller/ExpenseController.java
  server/src/main/java/com/rezero/inandout/expense/model/ExpenseInput.java
  server/src/main/java/com/rezero/inandout/expense/repository/ExpenseRepository.java
  server/src/main/java/com/rezero/inandout/expense/service/ExpenseService.java
  server/src/main/java/com/rezero/inandout/expense/service/impl/ExpenseServiceImpl.java
  server/src/test/java/com/rezero/inandout/expense/controller/ExpenseControllerTest.java
  server/src/test/java/com/rezero/inandout/expense/service/impl/ExpenseServiceImplTest.java
Labels: ✨ Feature, 📬 API, ✅ Test

#33 REFACTOR/차트 변경 상태 관련 로직 수정
  client/src/components/common/Header.js
  client/src/components/common/Screen.js
  client/src/components/login/Signin.js
  client/src/components/main/Report.js
  client/src/components/setting/ProfileChange.js
  package.json
Labels: 🌏 Deploy, 🔨 Refactor

#35 Income update
  server/src/main/java/com/rezero/inandout/income/controller/IncomeController.java
  server/src/main/java/com/rezero/inandout/income/model/IncomeInput.java
  server/src/main/java/com/rezero/inandout/income/repository/IncomeRepository.java
  server/src/main/java/com/rezero/inandout/income/service/IncomeService.java
  server/src/main/java/com/rezero/inandout/income/service/IncomeServiceImpl.java
  server/src/test/java/com/rezero/inandout/income/controller/IncomeControllerTest.java
  server/src/test/java/com/rezero/inandout/income/service/IncomeServiceImplTest.java
Labels: ✨ Feature, 📬 API, ✅ Test

#36 Member 정보 조회 API
  server/src/main/java/com/rezero/inandout/member/controller/MemberController.java
  server/src/main/java/com/rezero/inandout/member/service/MemberService.java
  server/src/main/java/com/rezero/inandout/member/service/MemberServiceImpl.java
  server/src/test/java/com/rezero/inandout/member/controller/MemberControllerTest.java
  server/src/test/java/com/rezero/inandout/member/service/MemberServiceImplTest.java
Labels: ✨ Feature, 📬 API, ✅ Test

#38 FEAT/보고서 페이지 그래프,표 추가
  client/package-lock.json
  client/package.json
  client/src/components/ErrorBoundary.js
  client/src/components/main/ChartCanvas.js
  client/src/components/main/Checkbox.js
  client/src/components/main/Report.js
  package-lock.json
  package.json
Labels: ✨ Feature

#41 Expense 삭제
  server/src/main/java/com/rezero/inandout/expense/controller/ExpenseController.java
  server/src/main/java/com/rezero/inandout/expense/model/DeleteExpenseInput.java
  server/src/main/java/com/rezero/inandout/expense/model/ExpenseInput.java
  server/src/main/java/com/rezero/inandout/expense/repository/ExpenseRepository.java
  server/src/main/java/com/rezero/inandout/expense/service/ExpenseService.java
  server/src/main/java/com/rezero/inandout/expense/service/impl/ExpenseServiceImpl.java
  server/src/test/java/com/rezero/inandout/expense/controller/ExpenseControllerTest.java
  server/src/test/java/com/rezero/inandout/expense/service/impl/ExpenseServiceImplTest.java
Labels: ✨ Feature, 📬 API, ✅ Test

#40 Income 삭제
  server/src/main/java/com/rezero/inandout/income/controller/IncomeController.java
  server/src/main/java/com/rezero/inandout/income/model/DeleteIncomeInput.java
  server/src/main/java/com/rezero/inandout/income/repository/IncomeRepository.java
  server/src/main/java/com/rezero/inandout/income/service/IncomeService.java
  server/src/main/java/com/rezero/inandout/income/service/IncomeServiceImpl.java
  server/src/test/java/com/rezero/inandout/income/controller/IncomeControllerTest.java
  server/src/test/java/com/rezero/inandout/income/service/IncomeServiceImplTest.java
Labels: ✨ Feature, 📬 API, ✅ Test

#39 Member update API, TEST
  server/src/main/java/com/rezero/inandout/member/controller/MemberController.java
  server/src/main/java/com/rezero/inandout/member/service/MemberServiceImpl.java
  server/src/test/java/com/rezero/inandout/member/controller/MemberControllerTest.java
  server/src/test/java/com/rezero/inandout/member/service/MemberServiceImplTest.java
Labels: ✨ Feature, 📬 API, ✅ Test

#48 FEAT/Login Global state
  client/package-lock.json
  client/package.json
  client/src/components/common/Header.js
  client/src/components/login/Login.js
  client/src/features/login.js
  client/src/index.js
  client/src/store.js
Labels: ✨ Feature

#51 REFACTOR/persist 관련 로직수정: persistStore store파일로 이동
  client/src/components/login/Login.js
  client/src/index.js
  client/src/store.js
Labels: 🔨 Refactor

#47 Income exception
  server/src/main/java/com/rezero/inandout/exception/errorcode/IncomeErrorCode.java
  server/src/main/java/com/rezero/inandout/income/model/DeleteIncomeInput.java
  server/src/main/java/com/rezero/inandout/income/service/IncomeServiceImpl.java
  server/src/test/java/com/rezero/inandout/income/controller/IncomeControllerTest.java
  server/src/test/java/com/rezero/inandout/income/service/IncomeServiceImplTest.java
Labels: ⚙ Setting, ✨ Feature, 🐞 BugFix, 📬 API

#49 FEAT/Expense Swagger 적용
  server/src/main/java/com/rezero/inandout/configuration/SwaggerConfig.java
  server/src/main/java/com/rezero/inandout/expense/controller/ExpenseController.java
Labels: ⚙ Setting, ✨ Feature

#52 FEAT /IncomeController Swagger 세팅
  server/src/main/java/com/rezero/inandout/income/controller/IncomeController.java
Labels: ✨ Feature

#53 CHORE /gitignore-data.sql 추가
  server/.gitignore
Labels: ⚙ Setting

#55 FEAT/수입지출 페이지 표 추가
  client/db.json
  client/package-lock.json
  client/package.json
  client/src/components/main/Inout.js
  client/src/db.json
  client/src/editor/DateEditor.js
  client/src/editor/dropDownEditor.js
Labels: ✨ Feature

#57 Income get orderbyfix
  server/Dockerfile
  server/src/main/java/com/rezero/inandout/income/repository/IncomeRepository.java
  server/src/main/java/com/rezero/inandout/income/service/IncomeServiceImpl.java
  server/src/test/java/com/rezero/inandout/income/service/IncomeServiceImplTest.java
Labels: 🐞 BugFix, 📬 API, 🔨 Refactor

#56 FEAT /Dockerfile 생성
  server/Dockerfile
Labels: 🌏 Deploy, 🥰 Accessibility

#54 FEAT/Expense 조회 기입일 순으로 조회되게끔 수정
  server/src/main/java/com/rezero/inandout/expense/repository/ExpenseRepository.java
  server/src/main/java/com/rezero/inandout/expense/service/impl/ExpenseServiceImpl.java
  server/src/test/java/com/rezero/inandout/expense/service/impl/ExpenseServiceImplTest.java
Labels: 🔨 Refactor

#58 FEAT/수입지출 저장/삭제, 보고서 수입/지출 버튼 추가
  client/src/components/main/Inout.js
  client/src/components/main/Report.js
Labels: ✨ Feature

#61 FEAT / QueryDsl config 작성
  server/build.gradle
  server/src/main/java/com/rezero/inandout/configuration/QueryDslConfig.java
Labels: ⚙ Setting, ✨ Feature

#59 Member 비밀번호 변경 API
  server/src/main/java/com/rezero/inandout/member/controller/MemberController.java
  server/src/main/java/com/rezero/inandout/member/model/ChangePasswordInput.java
  server/src/main/java/com/rezero/inandout/member/service/MemberService.java
  server/src/main/java/com/rezero/inandout/member/service/MemberServiceImpl.java
  server/src/test/java/com/rezero/inandout/member/controller/MemberControllerTest.java
  server/src/test/java/com/rezero/inandout/member/service/MemberServiceImplTest.java
Labels: ✨ Feature, 📬 API, ✅ Test

#64 Member login API, TEST, SecurityConfig 수정
  server/src/main/java/com/rezero/inandout/configuration/SecurityConfig.java
  server/src/main/java/com/rezero/inandout/member/controller/MemberController.java
  server/src/main/java/com/rezero/inandout/member/service/MemberService.java
  server/src/main/java/com/rezero/inandout/member/service/MemberServiceImpl.java
  server/src/test/java/com/rezero/inandout/member/controller/MemberControllerTest.java
  server/src/test/java/com/rezero/inandout/member/service/MemberServiceImplTest.java
Labels: ✨ Feature, 📬 API, ✅ Test

#60 Service_layer 추가
  server/src/main/java/com/rezero/inandout/expense/controller/ExpenseController.java
  server/src/main/java/com/rezero/inandout/expense/service/base/ExpenseService.java
  server/src/main/java/com/rezero/inandout/expense/service/base/impl/ExpenseServiceImpl.java
  server/src/main/java/com/rezero/inandout/expense/service/report/ExpenseReportService.java
  server/src/main/java/com/rezero/inandout/expense/service/report/impl/ExpenseReportServiceImpl.java
  server/src/main/java/com/rezero/inandout/expense/service/table/ExpenseTableService.java
  server/src/main/java/com/rezero/inandout/expense/service/table/impl/ExpenseTableServiceImpl.java
  server/src/main/java/com/rezero/inandout/income/controller/IncomeController.java
  server/src/main/java/com/rezero/inandout/income/service/base/IncomeService.java
  server/src/main/java/com/rezero/inandout/income/service/base/impl/IncomeServiceImpl.java
  server/src/main/java/com/rezero/inandout/income/service/report/IncomeReportService.java
  server/src/main/java/com/rezero/inandout/income/service/report/impl/IncomeReportServiceImpl.java
  server/src/main/java/com/rezero/inandout/income/service/table/IncomeTableService.java
  server/src/main/java/com/rezero/inandout/income/service/table/impl/IncomeTableServiceImpl.java
  server/src/test/java/com/rezero/inandout/expense/controller/ExpenseControllerTest.java
  server/src/test/java/com/rezero/inandout/expense/service/impl/ExpenseServiceImplTest.java
  server/src/test/java/com/rezero/inandout/income/controller/IncomeControllerTest.java
  server/src/test/java/com/rezero/inandout/income/service/IncomeServiceImplTest.java
Labels: ✨ Feature, 🔨 Refactor, ✅ Test

#62 FEAT/Calendar page
  client/package-lock.json
  client/package.json
  client/src/components/main/Calendar.js
  client/src/components/main/Diary.js
  client/src/components/main/FullCalendar.js
  client/src/components/main/WriteModal.js
  client/src/components/main/_styles.scss
Labels: ✨ Feature

#65 REFACTOR/Expense&Income Report 삭제
  server/src/main/java/com/rezero/inandout/expense/entity/MonthlyExpenseReport.java
  server/src/main/java/com/rezero/inandout/expense/repository/MonthlyExpenseReportRepository.java
  server/src/main/java/com/rezero/inandout/income/entity/MonthlyIncomeReport.java
Labels: 🔨 Refactor

#66 Member 예외 처리 & MemberException 적용
  server/src/main/java/com/rezero/inandout/exception/CustomExceptionHandler.java
  server/src/main/java/com/rezero/inandout/exception/MemberException.java
  server/src/main/java/com/rezero/inandout/exception/errorcode/MemberErrorCode.java
  server/src/main/java/com/rezero/inandout/exception/response/MemberErrorResponse.java
  server/src/main/java/com/rezero/inandout/member/controller/MemberController.java
  server/src/main/java/com/rezero/inandout/member/service/MemberServiceImpl.java
  server/src/test/java/com/rezero/inandout/member/controller/MemberControllerTest.java
  server/src/test/java/com/rezero/inandout/member/service/MemberServiceImplTest.java
Labels: ⚙ Setting, 🐞 BugFix, 📬 API, ✅ Test

#71 REFACTOR/ExpenseController 수정
  server/src/main/java/com/rezero/inandout/expense/controller/ExpenseController.java
Labels: 🔨 Refactor

#70 CHORE / deploy시 적용할 properties와 develop시 적용할 properties 구분.
  server/src/main/resources/application.properties
Labels: ⚙ Setting, 🌏 Deploy

#68 REFACTOR/API 테스트 준비 작업
  client/src/App.js
  client/src/components/common/DateHeader.js
  client/src/components/common/Layout.js
  client/src/components/common/Sidebar.js
  client/src/components/main/Calendar.js
  client/src/components/main/Diary.js
  client/src/components/main/FullCalendar.js
  client/src/components/main/Inout.js
  client/src/components/main/Report.js
  client/src/components/main/_styles.scss
  client/src/editor/DateEditor.js
  client/src/option/graphOptions.js
Labels: ✨ Feature, 🔨 Refactor

#73 CHORE / gitignore 수정
  server/.gitignore
  server/src/main/java/com/rezero/inandout/InandoutApplication.java
Labels: ⚙ Setting

#69 REFACTOR/ MemberController Swagger 세팅
  server/src/main/java/com/rezero/inandout/member/controller/MemberController.java
Labels: 🔨 Refactor, 🥰 Accessibility

#75 CHORE / application.properties 수정
  server/src/main/resources/application.properties
Labels: ⚙ Setting

#74 FEAT/report 패키지 세팅
  server/src/main/java/com/rezero/inandout/expense/service/report/ExpenseReportService.java
  server/src/main/java/com/rezero/inandout/expense/service/report/impl/ExpenseReportServiceImpl.java
  server/src/main/java/com/rezero/inandout/income/service/report/IncomeReportService.java
  server/src/main/java/com/rezero/inandout/income/service/report/impl/IncomeReportServiceImpl.java
  server/src/main/java/com/rezero/inandout/report/controller/ReportController.java
  server/src/main/java/com/rezero/inandout/report/model/ReportDto.java
  server/src/main/java/com/rezero/inandout/report/service/ReportService.java
  server/src/main/java/com/rezero/inandout/report/service/impl/ReportServiceImpl.java
Labels: ⚙ Setting

#76 FIX / Controller test 수정
  server/src/test/java/com/rezero/inandout/expense/controller/ExpenseControllerTest.java
  server/src/test/java/com/rezero/inandout/income/controller/IncomeControllerTest.java
  server/src/test/java/com/rezero/inandout/member/controller/MemberControllerTest.java
Labels: 🐞 BugFix, ✅ Test

#82 FIX/ @MockBean 중복 수정
  server/src/test/java/com/rezero/inandout/member/controller/MemberControllerTest.java
Labels: 🐞 BugFix, ✅ Test

#81 MemberStatus 추가 및 적용
  server/src/main/java/com/rezero/inandout/member/entity/Member.java
  server/src/main/java/com/rezero/inandout/member/model/MemberStatus.java
  server/src/main/java/com/rezero/inandout/member/service/MemberServiceImpl.java
Labels: ✨ Feature, 🔨 Refactor

#80 month expense report 구현
  server/src/main/java/com/rezero/inandout/report/controller/ReportController.java
  server/src/main/java/com/rezero/inandout/report/repository/ExpenseQueryRepository.java
  server/src/main/java/com/rezero/inandout/report/service/ReportService.java
  server/src/main/java/com/rezero/inandout/report/service/impl/ReportServiceImpl.java
  server/src/test/java/com/rezero/inandout/report/controller/ReportControllerTest.java
  server/src/test/java/com/rezero/inandout/report/repository/ExpenseQueryRepositoryTest.java
  server/src/test/java/com/rezero/inandout/report/service/impl/ReportServiceImplTest.java
Labels: ✨ Feature, 📬 API, ✅ Test

#83 FEAT/report_month_income 구현
  server/src/main/java/com/rezero/inandout/income/repository/IncomeQueryRepository.java
  server/src/main/java/com/rezero/inandout/report/controller/ReportController.java
  server/src/main/java/com/rezero/inandout/report/service/ReportService.java
  server/src/main/java/com/rezero/inandout/report/service/impl/ReportServiceImpl.java
  server/src/test/java/com/rezero/inandout/income/repository/IncomeQueryRepositoryTest.java
  server/src/test/java/com/rezero/inandout/report/controller/ReportControllerTest.java
  server/src/test/java/com/rezero/inandout/report/service/impl/ReportServiceImplTest.java
Labels: ✨ Feature, 📬 API, ✅ Test

#84 FIX/Report Conflict으로 인한 수정
  server/src/main/java/com/rezero/inandout/report/controller/ReportController.java
  server/src/main/java/com/rezero/inandout/report/service/ReportService.java
  server/src/main/java/com/rezero/inandout/report/service/impl/ReportServiceImpl.java
  server/src/test/java/com/rezero/inandout/report/controller/ReportControllerTest.java
  server/src/test/java/com/rezero/inandout/report/service/impl/ReportServiceImplTest.java
Labels: 🐞 BugFix

#86 Member 이메일 인증 API
  server/src/main/java/com/rezero/inandout/exception/errorcode/MemberErrorCode.java
  server/src/main/java/com/rezero/inandout/member/component/MailComponent.java
  server/src/main/java/com/rezero/inandout/member/controller/MemberController.java
  server/src/main/java/com/rezero/inandout/member/entity/Member.java
  server/src/main/java/com/rezero/inandout/member/repository/MemberRepository.java
  server/src/main/java/com/rezero/inandout/member/service/MemberService.java
  server/src/main/java/com/rezero/inandout/member/service/MemberServiceImpl.java
  server/src/test/java/com/rezero/inandout/member/controller/MemberControllerTest.java
  server/src/test/java/com/rezero/inandout/member/service/MemberServiceImplTest.java
Labels: ✨ Feature, 🐞 BugFix, 📬 API, ✅ Test

#88 Month income fix
  server/src/main/java/com/rezero/inandout/income/repository/IncomeQueryRepository.java
  server/src/main/java/com/rezero/inandout/income/service/base/IncomeService.java
  server/src/main/java/com/rezero/inandout/income/service/base/impl/IncomeServiceImpl.java
  server/src/main/java/com/rezero/inandout/report/service/impl/ReportServiceImpl.java
  server/src/test/java/com/rezero/inandout/income/repository/IncomeQueryRepositoryTest.java
  server/src/test/java/com/rezero/inandout/income/service/IncomeServiceImplTest.java
  server/src/test/java/com/rezero/inandout/report/service/impl/ReportServiceImplTest.java
Labels: 🔨 Refactor, ✅ Test

#89 FEAT/report, inout, calendar 기능 추가
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/components/main/Calendar.js
  client/src/components/main/Diary.js
  client/src/components/main/FullCalendar.js
  client/src/components/main/Inout.js
  client/src/components/main/Report.js
  client/src/db.json
  client/src/editor/DateEditor.js
  client/src/option/graphOptions.js
  package-lock.json
  package.json
Labels: ✨ Feature

#90 연간 지출 보고서 API 구현
  server/src/main/java/com/rezero/inandout/expense/repository/ExpenseQueryRepository.java
  server/src/main/java/com/rezero/inandout/expense/service/base/ExpenseService.java
  server/src/main/java/com/rezero/inandout/expense/service/base/impl/ExpenseServiceImpl.java
  server/src/main/java/com/rezero/inandout/report/controller/ReportController.java
  server/src/main/java/com/rezero/inandout/report/service/ReportService.java
  server/src/main/java/com/rezero/inandout/report/service/impl/ReportServiceImpl.java
  server/src/test/java/com/rezero/inandout/expense/repository/ExpenseQueryRepositoryTest.java
  server/src/test/java/com/rezero/inandout/expense/service/impl/ExpenseServiceImplTest.java
  server/src/test/java/com/rezero/inandout/report/controller/ReportControllerTest.java
  server/src/test/java/com/rezero/inandout/report/service/impl/ReportServiceImplTest.java
Labels: ✨ Feature, 📬 API, 🔨 Refactor, ✅ Test

#94 FEAT/report-get-yearly-total
  server/src/main/java/com/rezero/inandout/expense/service/base/ExpenseService.java
  server/src/main/java/com/rezero/inandout/expense/service/base/impl/ExpenseServiceImpl.java
  server/src/main/java/com/rezero/inandout/income/repository/IncomeQueryRepository.java
  server/src/main/java/com/rezero/inandout/income/service/base/IncomeService.java
  server/src/main/java/com/rezero/inandout/income/service/base/impl/IncomeServiceImpl.java
  server/src/main/java/com/rezero/inandout/report/controller/ReportController.java
  server/src/main/java/com/rezero/inandout/report/model/YearlyExpenseReportDto.java
  server/src/main/java/com/rezero/inandout/report/model/YearlyIncomeReportDto.java
  server/src/main/java/com/rezero/inandout/report/model/YearlyReportDto.java
  server/src/main/java/com/rezero/inandout/report/model/YearlyTotalReportDto.java
  server/src/main/java/com/rezero/inandout/report/service/ReportService.java
  server/src/main/java/com/rezero/inandout/report/service/impl/ReportServiceImpl.java
  server/src/test/java/com/rezero/inandout/expense/service/impl/ExpenseServiceImplTest.java
  server/src/test/java/com/rezero/inandout/income/service/IncomeServiceImplTest.java
  server/src/test/java/com/rezero/inandout/report/controller/ReportControllerTest.java
Labels: ✨ Feature, 📬 API, ✅ Test

#95 FEAT/Report 기능 전체 구현
  server/src/main/java/com/rezero/inandout/expense/repository/ExpenseQueryRepository.java
  server/src/main/java/com/rezero/inandout/expense/service/base/ExpenseService.java
  server/src/main/java/com/rezero/inandout/expense/service/base/impl/ExpenseServiceImpl.java
  server/src/main/java/com/rezero/inandout/income/repository/IncomeQueryRepository.java
  server/src/main/java/com/rezero/inandout/income/service/base/IncomeService.java
  server/src/main/java/com/rezero/inandout/income/service/base/impl/IncomeServiceImpl.java
  server/src/main/java/com/rezero/inandout/report/controller/ReportController.java
  server/src/main/java/com/rezero/inandout/report/model/YearlyExpenseReportDto.java
  server/src/main/java/com/rezero/inandout/report/model/YearlyIncomeReportDto.java
  server/src/main/java/com/rezero/inandout/report/model/YearlyTotalReportDto.java
  server/src/main/java/com/rezero/inandout/report/service/ReportService.java
  server/src/main/java/com/rezero/inandout/report/service/impl/ReportServiceImpl.java
  server/src/test/java/com/rezero/inandout/expense/repository/ExpenseQueryRepositoryTest.java
  server/src/test/java/com/rezero/inandout/expense/service/impl/ExpenseServiceImplTest.java
  server/src/test/java/com/rezero/inandout/income/repository/IncomeQueryRepositoryTest.java
  server/src/test/java/com/rezero/inandout/income/service/IncomeServiceImplTest.java
  server/src/test/java/com/rezero/inandout/report/controller/ReportControllerTest.java
  server/src/test/java/com/rezero/inandout/report/service/impl/ReportServiceImplTest.java
Labels: ✨ Feature, 📬 API

#96 FIX/ login test 코드, login(), loadByUsername() 수정
  server/src/main/java/com/rezero/inandout/member/service/MemberServiceImpl.java
  server/src/test/java/com/rezero/inandout/member/service/MemberServiceImplTest.java
Labels: 🐞 BugFix, 🔨 Refactor, ✅ Test

#97 REFACTOR/수입,지출,보고서 디자인 및 코드 수정
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/components/common/DateHeader.js
  client/src/components/common/Header.js
  client/src/components/common/Layout.js
  client/src/components/common/LeftSidebar.js
  client/src/components/common/Sidebar.js
  client/src/components/main/Calendar.js
  client/src/components/main/Checkbox.js
  client/src/components/main/Inout.js
  client/src/components/main/RadioButton.js
  client/src/components/main/Report.js
  client/src/components/main/TabPanel.js
  client/src/db.json
Labels: 🔨 Refactor

#99 FEAT/Diary 조회
  server/src/main/java/com/rezero/inandout/diary/controller/DiaryController.java
  server/src/main/java/com/rezero/inandout/diary/model/DiaryDto.java
  server/src/main/java/com/rezero/inandout/diary/repository/DiaryRepository.java
  server/src/main/java/com/rezero/inandout/diary/service/DiaryService.java
  server/src/main/java/com/rezero/inandout/diary/service/impl/DiaryServiceImpl.java
  server/src/test/java/com/rezero/inandout/diary/controller/DiaryControllerTest.java
  server/src/test/java/com/rezero/inandout/diary/service/impl/DiaryServiceImplTest.java
Labels: ✨ Feature, 📬 API, ✅ Test

#100 FEAT/calendar 조회 API 구현
  server/src/main/java/com/rezero/inandout/calendar/controller/CalendarController.java
  server/src/main/java/com/rezero/inandout/calendar/model/CalendarExpenseDto.java
  server/src/main/java/com/rezero/inandout/calendar/model/CalendarIncomeDto.java
  server/src/main/java/com/rezero/inandout/calendar/model/CalendarMonthlyDto.java
  server/src/main/java/com/rezero/inandout/calendar/service/CalendarService.java
  server/src/main/java/com/rezero/inandout/calendar/service/Impl/CalendarServiceImpl.java
  server/src/main/java/com/rezero/inandout/expense/repository/ExpenseQueryRepository.java
  server/src/main/java/com/rezero/inandout/expense/service/base/ExpenseService.java
  server/src/main/java/com/rezero/inandout/expense/service/base/impl/ExpenseServiceImpl.java
  server/src/main/java/com/rezero/inandout/income/repository/IncomeQueryRepository.java
  server/src/main/java/com/rezero/inandout/income/service/base/IncomeService.java
  server/src/main/java/com/rezero/inandout/income/service/base/impl/IncomeServiceImpl.java
  server/src/main/resources/application-dbsecret.properties
  server/src/test/java/com/rezero/inandout/calendar/controller/CalendarControllerTest.java
  server/src/test/java/com/rezero/inandout/calendar/service/Impl/CalendarServiceImplTest.java
  server/src/test/java/com/rezero/inandout/expense/service/impl/ExpenseServiceImplTest.java
  server/src/test/java/com/rezero/inandout/income/service/IncomeServiceImplTest.java
Labels: ✨ Feature, 📬 API, ✅ Test

#105 FEAT/Calendar get QueryTest
  server/src/test/java/com/rezero/inandout/expense/repository/ExpenseQueryRepositoryTest.java
  server/src/test/java/com/rezero/inandout/income/repository/IncomeQueryRepositoryTest.java
Labels: ✨ Feature, ✅ Test

#101 FEAT/S3 setting
  server/build.gradle
  server/src/main/java/com/rezero/inandout/configuration/AWSConfig.java
  server/src/main/resources/application.properties
Labels: ⚙ Setting, ✨ Feature

#102 Member 비밀번호 초기화 API
  server/src/main/java/com/rezero/inandout/exception/errorcode/MemberErrorCode.java
  server/src/main/java/com/rezero/inandout/member/controller/MemberController.java
  server/src/main/java/com/rezero/inandout/member/entity/Member.java
  server/src/main/java/com/rezero/inandout/member/model/ResetPasswordInput.java
  server/src/main/java/com/rezero/inandout/member/repository/MemberRepository.java
  server/src/main/java/com/rezero/inandout/member/service/MemberService.java
  server/src/main/java/com/rezero/inandout/member/service/MemberServiceImpl.java
  server/src/test/java/com/rezero/inandout/member/controller/MemberControllerTest.java
  server/src/test/java/com/rezero/inandout/member/service/MemberServiceImplTest.java
Labels: ✨ Feature, 🐞 BugFix, 📬 API, ✅ Test
