Repository RE-ZERO-In-And-Out/In-And-Out, pull requests merged in 2022-11, with the labels that each got.

#109 Member 수정 프로필 이미지 업로드 API
  server/src/main/java/com/rezero/inandout/member/controller/MemberController.java
  server/src/main/java/com/rezero/inandout/member/service/MemberService.java
  server/src/main/java/com/rezero/inandout/member/service/MemberServiceImpl.java
  server/src/test/java/com/rezero/inandout/member/controller/MemberControllerTest.java
  server/src/test/java/com/rezero/inandout/member/service/MemberServiceImplTest.java
Labels: ✨ Feature, 🐞 BugFix, 📬 API, ✅ Test

#110 FIX/(Detail)ExpenseCategory Entity 수정
  server/src/main/java/com/rezero/inandout/expense/entity/DetailExpenseCategory.java
  server/src/main/java/com/rezero/inandout/expense/entity/ExpenseCategory.java
Labels: 🐞 BugFix

#111 FIX/(Detail)Category Entity 수정
  server/src/main/java/com/rezero/inandout/expense/entity/DetailExpenseCategory.java
  server/src/main/java/com/rezero/inandout/expense/entity/ExpenseCategory.java
  server/src/main/java/com/rezero/inandout/income/entity/DetailIncomeCategory.java
  server/src/main/java/com/rezero/inandout/income/entity/IncomeCategory.java
Labels: 🐞 BugFix

#113 FEAT/Diary 수정 API
  server/src/main/java/com/rezero/inandout/diary/controller/DiaryController.java
  server/src/main/java/com/rezero/inandout/diary/model/UpdateDiaryInput.java
  server/src/main/java/com/rezero/inandout/diary/repository/DiaryRepository.java
  server/src/main/java/com/rezero/inandout/diary/service/DiaryService.java
  server/src/main/java/com/rezero/inandout/diary/service/impl/DiaryServiceImpl.java
  server/src/main/java/com/rezero/inandout/exception/errorcode/DiaryErrorCode.java
  server/src/test/java/com/rezero/inandout/diary/controller/DiaryControllerTest.java
  server/src/test/java/com/rezero/inandout/diary/service/impl/DiaryServiceImplTest.java
Labels: ✨ Feature, 📬 API, ✅ Test

#114 FEAT/Diary 삭제
  server/src/main/java/com/rezero/inandout/diary/controller/DiaryController.java
  server/src/main/java/com/rezero/inandout/diary/model/DeleteDiaryInput.java
  server/src/main/java/com/rezero/inandout/diary/service/DiaryService.java
  server/src/main/java/com/rezero/inandout/diary/service/impl/DiaryServiceImpl.java
  server/src/test/java/com/rezero/inandout/diary/controller/DiaryControllerTest.java
  server/src/test/java/com/rezero/inandout/diary/service/impl/DiaryServiceImplTest.java
Labels: ✨ Feature, 📬 API, ✅ Test

#115 FEAT/excel-download-month
  server/build.gradle
  server/src/main/java/com/rezero/inandout/excel/component/ExcelDownloadComponent.java
  server/src/main/java/com/rezero/inandout/excel/controller/ExcelController.java
  server/src/main/java/com/rezero/inandout/excel/model/ExpenseExcelDto.java
  server/src/main/java/com/rezero/inandout/excel/model/IncomeExcelDto.java
  server/src/main/java/com/rezero/inandout/excel/service/ExcelService.java
  server/src/main/java/com/rezero/inandout/excel/service/impl/ExcelServiceImpl.java
  server/src/main/java/com/rezero/inandout/expense/model/ExpenseDto.java
  server/src/main/java/com/rezero/inandout/expense/service/base/ExpenseService.java
  server/src/main/java/com/rezero/inandout/expense/service/base/impl/ExpenseServiceImpl.java
  server/src/main/java/com/rezero/inandout/income/model/IncomeDto.java
Labels: ✨ Feature, 📬 API

#117 FIX/DiaryService 테스트코드 수정
  server/src/test/java/com/rezero/inandout/diary/service/impl/DiaryServiceImplTest.java
Labels: 🐞 BugFix

#116 Member 이미지 업로드 API 추가 및 오류 수정
  server/src/main/java/com/rezero/inandout/member/service/MemberServiceImpl.java
  server/src/test/java/com/rezero/inandout/member/controller/MemberControllerTest.java
  server/src/test/java/com/rezero/inandout/member/service/MemberServiceImplTest.java
Labels: ✨ Feature, 🐞 BugFix, 📬 API, ✅ Test

#119 FEAT/ Log setting
  server/build.gradle
  server/src/main/java/com/rezero/inandout/excel/component/ExcelDownloadComponent.java
  server/src/main/resources/logback-spring.xml
Labels: ⚙ Setting, ✨ Feature

#120 REFACTOR / Member 예외 처리 추가 및 적용
  server/src/main/java/com/rezero/inandout/exception/CustomExceptionHandler.java
  server/src/main/java/com/rezero/inandout/exception/errorcode/MemberErrorCode.java
  server/src/main/java/com/rezero/inandout/member/controller/MemberController.java
  server/src/main/java/com/rezero/inandout/member/service/MemberServiceImpl.java
Labels: 🐞 BugFix, 🔨 Refactor

#121 REFACTOR/디자인 수정, 보고서, 로그인, 회원가입, 설정 화면 api 연동 추가
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/components/common/DateHeader.js
  client/src/components/common/Header.js
  client/src/components/common/Layout.js
  client/src/components/common/LeftSidebar.js
  client/src/components/common/Screen.js
  client/src/components/login/IdentifyEmail.js
  client/src/components/login/IdentifyPhone.js
  client/src/components/login/Login.js
  client/src/components/login/RecoverInitiate.js
  client/src/components/login/Signin.js
  client/src/components/main/Report.js
  client/src/components/route/privateRoute.js
  client/src/components/route/publicRoute.js
  client/src/components/setting/PasswordChange.js
  client/src/components/setting/ProfileChange.js
  client/src/components/setting/Signout.js
  client/src/db.json
  client/src/editor/dropDownEditor.js
  client/src/img/logo3.png
  client/src/option/graphOptions.js
  client/src/setupProxy.js
  client/src/store/store.js
Labels: ✨ Feature, 📬 API, 🔨 Refactor

#122 FEAT/Redis setting
  server/build.gradle
  server/src/main/java/com/rezero/inandout/configuration/RedisConfig.java
  server/src/main/java/com/rezero/inandout/exception/CustomExceptionHandler.java
  server/src/main/java/com/rezero/inandout/exception/RedisException.java
  server/src/main/java/com/rezero/inandout/exception/response/RedisErrorResponse.java
  server/src/main/java/com/rezero/inandout/redis/RedisService.java
  server/src/main/java/com/rezero/inandout/redis/RedisServiceImpl.java
  server/src/main/resources/application.properties
Labels: ⚙ Setting, ✨ Feature

#124 Redis 수정
  server/src/main/java/com/rezero/inandout/exception/CustomExceptionHandler.java
  server/src/main/java/com/rezero/inandout/redis/RedisServiceImpl.java
Labels: 🐞 BugFix

#123 FEAT/log 적용
  server/src/main/java/com/rezero/inandout/diary/service/impl/DiaryServiceImpl.java
  server/src/main/java/com/rezero/inandout/excel/component/ExcelDownloadComponent.java
  server/src/main/java/com/rezero/inandout/excel/service/impl/ExcelServiceImpl.java
  server/src/main/java/com/rezero/inandout/exception/CustomExceptionHandler.java
  server/src/main/java/com/rezero/inandout/member/component/MailComponent.java
  server/src/main/java/com/rezero/inandout/member/service/MemberServiceImpl.java
Labels: ✨ Feature, 🔨 Refactor

#126 FEAT/수입,지출 api 추가
  client/.env.development
  client/.env.production
  client/src/components/common/Header.js
  client/src/components/login/IdentifyEmail.js
  client/src/components/login/IdentifyPhone.js
  client/src/components/login/Login.js
  client/src/components/login/RecoverInitiate.js
  client/src/components/login/Signin.js
  client/src/components/main/Inout.js
  client/src/components/main/Report.js
  client/src/components/setting/PasswordChange.js
  client/src/components/setting/ProfileChange.js
  client/src/editor/DateEditor.js
  client/src/editor/dropDownEditor.js
  client/src/store/store.js
  client/src/utils/graphOptions.js
Labels: ✨ Feature, 🌏 Deploy, 🐞 BugFix, 📬 API

#125 Category 조회 redis
  server/src/main/java/com/rezero/inandout/expense/service/base/impl/ExpenseServiceImpl.java
  server/src/main/java/com/rezero/inandout/income/service/base/impl/IncomeServiceImpl.java
  server/src/test/java/com/rezero/inandout/expense/service/impl/ExpenseServiceImplTest.java
  server/src/test/java/com/rezero/inandout/income/service/IncomeServiceImplTest.java
Labels: ✨ Feature, 📬 API, ✅ Test

#129 FEAT/Excel yearly export
  server/src/main/java/com/rezero/inandout/excel/component/ExcelDownloadComponent.java
  server/src/main/java/com/rezero/inandout/excel/controller/ExcelController.java
  server/src/main/java/com/rezero/inandout/excel/model/YearlyExcelDto.java
  server/src/main/java/com/rezero/inandout/excel/service/ExcelService.java
  server/src/main/java/com/rezero/inandout/excel/service/impl/ExcelServiceImpl.java
  server/src/main/java/com/rezero/inandout/member/service/MemberServiceImpl.java
Labels: ✨ Feature, 📬 API, ✅ Test

#127 OAuth 2.0 (1) 기본 설정
  server/src/main/java/com/rezero/inandout/configuration/SecurityConfig.java
  server/src/main/java/com/rezero/inandout/configuration/auth/PrincipalDetails.java
  server/src/main/java/com/rezero/inandout/configuration/oauth/PrincipalOauth2UserService.java
  server/src/main/java/com/rezero/inandout/configuration/oauth/provider/GoogleUserInfo.java
  server/src/main/java/com/rezero/inandout/configuration/oauth/provider/NaverUserInfo.java
  server/src/main/java/com/rezero/inandout/configuration/oauth/provider/OAuth2UserInfo.java
  server/src/main/java/com/rezero/inandout/exception/errorcode/MemberErrorCode.java
  server/src/main/java/com/rezero/inandout/member/controller/MemberController.java
  server/src/main/java/com/rezero/inandout/member/entity/Member.java
  server/src/main/java/com/rezero/inandout/member/model/OauthMemberInput.java
  server/src/main/java/com/rezero/inandout/member/repository/MemberRepository.java
  server/src/main/java/com/rezero/inandout/member/service/impl/MemberServiceImpl.java
  server/src/main/resources/application.properties
  server/src/test/java/com/rezero/inandout/calendar/controller/CalendarControllerTest.java
  server/src/test/java/com/rezero/inandout/diary/controller/DiaryControllerTest.java
  server/src/test/java/com/rezero/inandout/expense/controller/ExpenseControllerTest.java
  server/src/test/java/com/rezero/inandout/income/controller/IncomeControllerTest.java
  server/src/test/java/com/rezero/inandout/member/controller/MemberControllerTest.java
  server/src/test/java/com/rezero/inandout/member/service/MemberServiceImplTest.java
  server/src/test/java/com/rezero/inandout/report/controller/ReportControllerTest.java
Labels: ✨ Feature, 🐞 BugFix, 🔨 Refactor, ✅ Test

#131 FEAT/지출 관련 API들의 Body에 대한 Validation 적용
  server/src/main/java/com/rezero/inandout/expense/controller/ExpenseController.java
  server/src/main/java/com/rezero/inandout/expense/model/DeleteExpenseInput.java
  server/src/main/java/com/rezero/inandout/expense/model/ExpenseInput.java
Labels: ✨ Feature

#135 FEAT/수입 관련 Valid 적용
  server/src/main/java/com/rezero/inandout/income/controller/IncomeController.java
  server/src/main/java/com/rezero/inandout/income/model/DeleteIncomeInput.java
  server/src/main/java/com/rezero/inandout/income/model/IncomeInput.java
Labels: ✨ Feature, 🔨 Refactor

#137 FIX/Income valid
  server/src/main/java/com/rezero/inandout/income/model/IncomeInput.java
  server/src/main/resources/application.properties
Labels: 🐞 BugFix

#136 FEAT/AWS S3 Service log 적용
  server/src/main/java/com/rezero/inandout/awss3/AwsS3ServiceImpl.java
Labels: ✨ Feature

#138 FIX/diary controller test 수정
  server/src/test/java/com/rezero/inandout/diary/controller/DiaryControllerTest.java
Labels: 🐞 BugFix

#139 Member OAuth 2.0 (2) Handler 구현
  server/src/main/java/com/rezero/inandout/configuration/SecurityConfig.java
  server/src/main/java/com/rezero/inandout/configuration/UserAuthenticationFailureHandler.java
  server/src/main/java/com/rezero/inandout/configuration/UserAuthenticationSuccessHandler.java
  server/src/main/java/com/rezero/inandout/member/service/impl/MemberServiceImpl.java
Labels: ✨ Feature, 🐞 BugFix, 🔨 Refactor

#140 FIX/test 오류 수정
  server/src/test/java/com/rezero/inandout/calendar/controller/CalendarControllerTest.java
  server/src/test/java/com/rezero/inandout/diary/controller/DiaryControllerTest.java
  server/src/test/java/com/rezero/inandout/expense/controller/ExpenseControllerTest.java
  server/src/test/java/com/rezero/inandout/member/controller/MemberControllerTest.java
  server/src/test/java/com/rezero/inandout/report/controller/ReportControllerTest.java
Labels: 🐞 BugFix, ✅ Test

#141 REFACTOR/ 멤버변수 oauthUsername 삭제
  server/src/main/java/com/rezero/inandout/configuration/oauth/PrincipalOauth2UserService.java
  server/src/main/java/com/rezero/inandout/member/entity/Member.java
Labels: 🔨 Refactor

#142 FEAT/local 에서 rds - mysql 사용하는 세팅 추가
  server/src/main/resources/application.properties
Labels: ⚙ Setting

#144 FIX/diaryService 일기 사진 변경 안했을 때 기존 사진 유지하도록 수정
  server/src/main/java/com/rezero/inandout/diary/service/impl/DiaryServiceImpl.java
Labels: 🐞 BugFix

#143 FEAT/CORS 세팅
  server/src/main/java/com/rezero/inandout/configuration/WebConfig.java
Labels: 💻 CrossBrowsing

#150 FIX/Cors and url
  server/src/main/java/com/rezero/inandout/configuration/CorsProperties.java
  server/src/main/java/com/rezero/inandout/configuration/SecurityConfig.java
  server/src/main/java/com/rezero/inandout/configuration/UserAuthenticationSuccessHandler.java
  server/src/main/java/com/rezero/inandout/configuration/WebConfig.java
  server/src/main/resources/application.properties
Labels: 💻 CrossBrowsing, 🥰 Accessibility

#146 FIX/diaryService 일기 수정 중 사진 삭제 버튼 눌렀을 때 s3이미지 삭제, key는 ""으로 되도록 수정
  server/src/main/java/com/rezero/inandout/diary/service/impl/DiaryServiceImpl.java
Labels: 🐞 BugFix

#147 FIX/diary input 클래스 어노테이션 수정
  server/src/main/java/com/rezero/inandout/diary/model/AddDiaryInput.java
  server/src/main/java/com/rezero/inandout/diary/model/DeleteDiaryInput.java
  server/src/main/java/com/rezero/inandout/diary/model/UpdateDiaryInput.java
Labels: 🐞 BugFix

#148 FIX/expense input 클래스 어노테이션 수정
  server/src/main/java/com/rezero/inandout/expense/model/DeleteExpenseInput.java
  server/src/main/java/com/rezero/inandout/expense/model/ExpenseInput.java
Labels: 🐞 BugFix

#145 Member OAuth (4) 에러 수정
  server/src/main/java/com/rezero/inandout/configuration/SecurityConfig.java
  server/src/main/java/com/rezero/inandout/configuration/UserAuthenticationSuccessHandler.java
  server/src/main/java/com/rezero/inandout/configuration/auth/PrincipalDetails.java
  server/src/main/java/com/rezero/inandout/configuration/oauth/PrincipalOauth2UserService.java
  server/src/main/java/com/rezero/inandout/configuration/oauth/provider/GoogleUserInfo.java
  server/src/main/java/com/rezero/inandout/configuration/oauth/provider/NaverUserInfo.java
  server/src/main/java/com/rezero/inandout/configuration/oauth/provider/OAuth2UserInfo.java
  server/src/main/java/com/rezero/inandout/member/entity/Member.java
  server/src/main/java/com/rezero/inandout/member/model/MemberRole.java
  server/src/main/java/com/rezero/inandout/member/model/OauthMemberInput.java
  server/src/main/java/com/rezero/inandout/member/repository/MemberRepository.java
  server/src/main/java/com/rezero/inandout/member/service/impl/MemberServiceImpl.java
Labels: ⚙ Setting, ✨ Feature, 🐞 BugFix, 🔨 Refactor

#151 FEAT/Cors filter setting
  server/src/main/java/com/rezero/inandout/configuration/CorsProperties.java
  server/src/main/java/com/rezero/inandout/configuration/WebConfig.java
  server/src/main/java/com/rezero/inandout/filter/CorsFilter.java
  server/src/main/resources/application.properties
Labels: ✨ Feature, 💻 CrossBrowsing, 📬 API, 🥰 Accessibility

#153 FIX/ExcelController 매핑 url 변경
  server/src/main/java/com/rezero/inandout/excel/controller/ExcelController.java
Labels: 🐞 BugFix

#154 FIX/memberserviceImpl
  server/src/main/java/com/rezero/inandout/member/service/impl/MemberServiceImpl.java
Labels: 🐞 BugFix

#155 FIX/income-valid 수정
  server/src/main/java/com/rezero/inandout/income/model/IncomeInput.java
Labels: 🐞 BugFix

#156 FIX/Diary 수정
  server/src/main/java/com/rezero/inandout/diary/model/AddDiaryInput.java
  server/src/main/java/com/rezero/inandout/diary/model/UpdateDiaryInput.java
  server/src/main/java/com/rezero/inandout/diary/service/impl/DiaryServiceImpl.java
Labels: 🐞 BugFix

#159 FIX/ ExpenseInput LocalDate에 있는 @PastOrPresent 삭제, @NotNull 추가
  server/src/main/java/com/rezero/inandout/expense/model/ExpenseInput.java
Labels: 🐞 BugFix

#160 FIX/ 메모 삭제
  server/src/main/java/com/rezero/inandout/member/model/JoinMemberInput.java
Labels: 🐞 BugFix

#162 FIX/ResponseEntity 수정
  server/src/main/java/com/rezero/inandout/calendar/controller/CalendarController.java
  server/src/main/java/com/rezero/inandout/diary/controller/DiaryController.java
  server/src/main/java/com/rezero/inandout/expense/controller/ExpenseController.java
  server/src/main/java/com/rezero/inandout/income/controller/IncomeController.java
  server/src/main/java/com/rezero/inandout/member/controller/MemberController.java
  server/src/main/java/com/rezero/inandout/report/controller/ReportController.java
Labels: 🐞 BugFix

#163 FIX/DiaryService 사진 안넣을 경우 수정
  server/src/main/java/com/rezero/inandout/diary/service/impl/DiaryServiceImpl.java
Labels: 🐞 BugFix

#164 Member validation 수정
  server/src/main/java/com/rezero/inandout/configuration/oauth/PrincipalOauth2UserService.java
  server/src/main/java/com/rezero/inandout/exception/errorcode/MemberErrorCode.java
  server/src/main/java/com/rezero/inandout/member/repository/MemberRepository.java
  server/src/main/java/com/rezero/inandout/member/service/impl/MemberServiceImpl.java
  server/src/test/java/com/rezero/inandout/member/service/MemberServiceImplTest.java
Labels: 🐞 BugFix, 🔨 Refactor

#165 FIX/SecurityConfig에 CORS 세팅 및 Filter클래스 삭제
  server/src/main/java/com/rezero/inandout/configuration/SecurityConfig.java
  server/src/main/java/com/rezero/inandout/filter/CorsFilter.java
Labels: 🐞 BugFix, 💻 CrossBrowsing, 🥰 Accessibility

#166 FIX/ redirect url 수정
  server/src/main/java/com/rezero/inandout/configuration/SecurityConfig.java
  server/src/main/java/com/rezero/inandout/configuration/UserAuthenticationSuccessHandler.java
  server/src/main/resources/application.properties
Labels: 🐞 BugFix

#167 FIX/DiaryService deleteFile, nullFile 변수의 초기값 수정
  server/src/main/java/com/rezero/inandout/diary/service/impl/DiaryServiceImpl.java
Labels: 🐞 BugFix

#168 구글 로그인 시, url 변경
  server/src/main/java/com/rezero/inandout/configuration/UserAuthenticationSuccessHandler.java
  server/src/main/resources/application.properties
Labels: 🔨 Refactor

#170 FIX/ url 변수 EC2 주소로 수정
  server/src/main/resources/application.properties
Labels: 🐞 BugFix

#171 FIX/연간보고서 엑셀 출력 API 수정
  server/src/main/java/com/rezero/inandout/excel/component/ExcelDownloadComponent.java
  server/src/main/java/com/rezero/inandout/excel/model/YearlyExcelDto.java
  server/src/main/java/com/rezero/inandout/excel/service/impl/ExcelServiceImpl.java
Labels: 🐞 BugFix

#172 FEAT/ OAuth 회원 로그인 후, 로그인한 회원의 oauthUsername을 url에 포함시켜서 post 매핑
  server/src/main/java/com/rezero/inandout/configuration/UserAuthenticationSuccessHandler.java
  server/src/main/java/com/rezero/inandout/member/controller/MemberController.java
  server/src/main/resources/application.properties
Labels: ✨ Feature, 📬 API

#174 FIX/캘린더 조회 API 버그 수정
  server/src/main/java/com/rezero/inandout/expense/repository/ExpenseQueryRepository.java
  server/src/test/java/com/rezero/inandout/expense/repository/ExpenseQueryRepositoryTest.java
Labels: 🐞 BugFix

#176 FIX/ 변수명 properties와 일치하도록 수정
  server/src/main/java/com/rezero/inandout/configuration/UserAuthenticationSuccessHandler.java
Labels: 🐞 BugFix

#177 FIX/redirect url 수정
  server/src/main/resources/application.properties
Labels: 🐞 BugFix

#178 FIX/ properties 파일 로컬 버전에 ec2.ip.address 추가, 프론트 url에서 "api" 제거
  server/src/main/resources/application.properties
Labels: 🐞 BugFix

#180 FIX/ properties에 구글, 네이버 url 영문으로 통일
  server/src/main/resources/application.properties
Labels: 🐞 BugFix, 🔨 Refactor

#182 FEAT/CORS-ORIGIN 주소 추가
  server/src/main/java/com/rezero/inandout/configuration/SecurityConfig.java
Labels: 💻 CrossBrowsing

#183 FIX/@Transactional 어노테이션 추가
  server/src/main/java/com/rezero/inandout/report/service/impl/ReportServiceImpl.java
Labels: 🐞 BugFix

#184 Feat/GET-MonthlyReport
  server/src/main/java/com/rezero/inandout/calendar/model/CalendarMonthlyDto.java
  server/src/main/java/com/rezero/inandout/calendar/service/Impl/CalendarServiceImpl.java
  server/src/test/java/com/rezero/inandout/calendar/service/Impl/CalendarServiceImplTest.java
Labels: ✨ Feature, 📬 API, ✅ Test

#185 FIX/ 모든 IP 주소를 DNS로 변경
  server/src/main/java/com/rezero/inandout/configuration/SecurityConfig.java
  server/src/main/resources/application.properties
Labels: 🐞 BugFix, 🔨 Refactor

#186 FEAT/DiaryService 메서드에 트랜젝션 적용
  server/src/main/java/com/rezero/inandout/diary/service/impl/DiaryServiceImpl.java
Labels: ✨ Feature

#187 FEAT/ExpenseService 메서드에 트랜젝션 적용
  server/src/main/java/com/rezero/inandout/expense/service/base/impl/ExpenseServiceImpl.java
  server/src/main/java/com/rezero/inandout/expense/service/table/impl/ExpenseTableServiceImpl.java
Labels: ✨ Feature

#188 FEAT/ReportService 메서드에 트랜젝션 적용
  server/src/main/java/com/rezero/inandout/report/service/impl/ReportServiceImpl.java
Labels: ✨ Feature

#192 FIX/수입 지출 캘린더, null 입력 버그 수정
  client/src/components/login/Login.js
  client/src/components/main/Inout.js
  client/src/components/main/Report.js
  client/src/editor/DateEditor.js
Labels: ✨ Feature, 🐞 BugFix, 📬 API

#193 REFACTOR/GetReport 쿼리 개선 및 서비스 메서드 수정
  server/src/main/java/com/rezero/inandout/income/repository/IncomeQueryRepository.java
  server/src/main/java/com/rezero/inandout/income/service/base/impl/IncomeServiceImpl.java
  server/src/main/java/com/rezero/inandout/report/controller/ReportController.java
  server/src/main/java/com/rezero/inandout/report/model/YearlyReportDto.java
Labels: ✨ Feature, 🔨 Refactor

#195 REFACTOR/Report get refactoring
  server/src/main/java/com/rezero/inandout/expense/repository/ExpenseQueryRepository.java
  server/src/main/java/com/rezero/inandout/expense/service/base/impl/ExpenseServiceImpl.java
  server/src/main/java/com/rezero/inandout/report/service/impl/ReportServiceImpl.java
Labels: 🐞 BugFix, 🔨 Refactor

#196 REFACTOR/get-report-second
  server/src/main/java/com/rezero/inandout/expense/repository/ExpenseQueryRepository.java
  server/src/main/java/com/rezero/inandout/expense/service/base/impl/ExpenseServiceImpl.java
  server/src/main/java/com/rezero/inandout/income/repository/IncomeQueryRepository.java
  server/src/main/java/com/rezero/inandout/income/service/base/impl/IncomeServiceImpl.java
  server/src/main/java/com/rezero/inandout/report/controller/ReportController.java
  server/src/test/java/com/rezero/inandout/expense/repository/ExpenseQueryRepositoryTest.java
  server/src/test/java/com/rezero/inandout/expense/service/impl/ExpenseServiceImplTest.java
  server/src/test/java/com/rezero/inandout/income/repository/IncomeQueryRepositoryTest.java
  server/src/test/java/com/rezero/inandout/income/service/IncomeServiceImplTest.java
Labels: 🔨 Refactor, ✅ Test

#198 Report get 수정
  server/src/main/java/com/rezero/inandout/expense/repository/ExpenseQueryRepository.java
  server/src/main/java/com/rezero/inandout/income/repository/IncomeQueryRepository.java
  server/src/test/java/com/rezero/inandout/expense/repository/ExpenseQueryRepositoryTest.java
  server/src/test/java/com/rezero/inandout/income/repository/IncomeQueryRepositoryTest.java
Labels: ✨ Feature, 🐞 BugFix, ✅ Test

#200 FIX/ 기존 코드 삭제
  server/src/main/java/com/rezero/inandout/member/service/impl/MemberServiceImpl.java
Labels: 🐞 BugFix

#199 FEAT/ 이메일 전송 시 비동기화 기능 추가
  server/src/main/java/com/rezero/inandout/configuration/AsyncConfig.java
  server/src/main/java/com/rezero/inandout/member/component/MailComponent.java
Labels: ✨ Feature

#203 CHORE/RELEASE-SNAPSHOT-1.0.0
  server/Dockerfile
  server/build.gradle
Labels: 🌏 Deploy

#202 CHORE/도커파일에 VM 옵션 추가
  server/Dockerfile
Labels: 🌏 Deploy

#210 REFACTOR/ 회원 로그인 시 쿼리가 중복해서 나가지 않도록 최적화
  server/src/main/java/com/rezero/inandout/member/service/impl/MemberServiceImpl.java
Labels: 🔨 Refactor

#213 REFACTOR/Fetch를 Lazy로 하여 쿼리 개선
  server/src/main/java/com/rezero/inandout/income/entity/Income.java
Labels: 🔨 Refactor
